### ISSUE TITLE
Possible to get a list of messages?

### ISSUE THREAD

**Issue by rotsee** [Philipp15b/php-i18n#12]
Is there any way to get a list of messages used programmatically?

Alternatively, is there any way to synamically build message names? `${var}` syntax doesn't work here, but maybe there are other ways?

**Comment by Philipp15b** [comment]
At the moment enumerating messages is not available through the php-i18n API. You could, however, use [PHP reflection](http://php.net/manual/en/reflectionclass.getconstants.php) on the generated `L` class.

Dynamically building message names isn't possible through php-i18n's API either, but maybe there's some obscure PHP syntax I don't know about.

**Comment by rotsee** [comment]
Ok, thanks!

I'm closing this thread as it's not really a feature request (the whole point with the library, after all, is simplicity), just wanted to check if there was something I had missed.
