### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by tbreuss** [Philipp15b/php-i18n#15]
Composer support would be nice. Are there any plans to do so?

**Comment by Philipp15b** [comment]
No, I don't use composer personally. But I'd happily accept a pull request for this.

**Comment by szakalq** [comment]
see here: https://github.com/szakalq/php-i18n

**Comment by tbreuss** [comment]
:+1:

**Comment by Philipp15b** [comment]
@monbro 

[php-18n is now on packagist :star:](https://packagist.org/packages/philipp15b/php-i18n).

**Comment by monbro** [comment]
Awesome!!

**Comment by tbreuss** [comment]
Thanks!
