### ISSUE TITLE
Function calls do not behave according to the documentation

### ISSUE THREAD

**Issue by bgarret** [Philipp15b/php-i18n#17]
The underlying code uses `vprintf` and outputs the resulting translation directly, instead of returning it.

The following example in the documentation will output the string, followed by its length, which is obviously wrong : 

``` php
echo L::last_modified("today");
```

To fix this, use vsprintf, which behaves the same as vprintf but returns the string instead of outputting it directly.

**Comment by Philipp15b** [comment]
Thanks!
