### ISSUE TITLE
vsprintf

### ISSUE THREAD

**Issue by bjlotus** [Philipp15b/php-i18n#18]
I've been trying the class for a while and seems to work pretty well, so thanks for coding this :smile:
The only issue I've found is around vsprintf.

I had to change `line 161` in order for it to work, where it says:

`$compiled .= 'vsprintf(constant("self::" . $string), $args);' . "\n";`

to:

`$compiled .= 'return vsprintf(constant("self::" . $string), $args);' . "\n";`

Let me know if that makes sense or if I'm missing something.
Cheers!

**Comment by Philipp15b** [comment]
You're right, thanks.
