### ISSUE TITLE
missing dynamic constants support

### ISSUE THREAD

**Issue by Spyna** [Philipp15b/php-i18n#20]
there is no support for dynamic calls to the derived class, I suggest to add the method "get". 

I changed the class by modifying this  

$compiled = "<?php class " . $this->prefix . " {\n";
$compiled .= $this->compile($config);
$compiled .= 'public static function __callStatic($string, $args) {' . "\n";
$compiled .= '    return vsprintf(constant("self::" . $string), $args);' . "\n";
$compiled .= "}\n";

into this:

$compiled = "<?php class " . $this->prefix . " {\n";
$compiled .= $this->compile($config);
$compiled .= 'public static function __callStatic($string, $args) {' . "\n";
$compiled .= '    return vsprintf(constant("self::" . $string), $args);' . "\n";
$compiled .= "}\n";
$compiled .= 'public static function get($string) {' . "\n";
$compiled .= '    return constant("self::" . $string);' . "\n";
$compiled .= "}\n}";

so now I can call L::get("myconstant")

**Comment by dvlife3** [comment]
I have the same problem, but in my case I read from DB an event_id that represents a string with arguments so I've added the function:

$compiled .= 'public static function get($string, $args=array()) {' . "\n";
$compiled .= '    return vsprintf(constant("self::" . $string), $args);' . "\n";
$compiled .= "}\n";

So I can call:
L::get("myconstant");
L::get("myconstant",array('arg1','arg2','arg3'));

**Comment by B7th** [comment]
Actually, calling `constant('L::'.$string);` works just as great without adding any function. It may not be pretty, but it reminds us that the Language class should really only be mainly constants.

As for the vsprinted dynamic version, I believe it should again remain a rarer case and can actually be done when necessary with the uglier `vsprint(constant('L::'.$string),$args);`

**Comment by Philipp15b** [comment]
I agree with @B7th. This library is supposed to be simple and constants are its main use case. But if someone were to submit a pull request with the required changes and documentation, I would merge.

**Comment by B7th** [comment]
I found a funny and useful loophole. Classes can share namespace with functions, so I made a pull request that makes it look like the class is invoked `L("string".$name);`

**Comment by Philipp15b** [comment]
Closed by #26.
