### ISSUE TITLE
UTF 8

### ISSUE THREAD

**Issue by davidtim** [Philipp15b/php-i18n#22]
I'm sure is it a UTF 8 problem, but i got ��� when change language

**Comment by marijnz0r** [comment]
I've got the same problem, is there any solution to this?

**Comment by marlonmaxwellourencoleite** [comment]
Hello,

I'm using UTF-8 characters in lang.ini file.
It works perfectly.
Check whether the translation file you're formatting UTF-8 WITHOUT BOM.

**Comment by marlonmleite** [comment]
Hello,

I'm using UTF-8 characters in lang.ini file.
It works perfectly.
Check whether the translation file you're formatting UTF-8 WITHOUT BOM.

**Comment by Philipp15b** [comment]
I'm assuming that's the solution. Closing. Thanks @marlonmleite.
