### ISSUE TITLE
"No language file was found" (but they are there..)

### ISSUE THREAD

**Issue by Zeebroek** [Philipp15b/php-i18n#27]
Dear 

I've got the following error. It seems that my language files are not included, but if I include them at the same path, they are.
Error message looks like this:
![image](https://cloud.githubusercontent.com/assets/13527958/13932184/3195feca-efa7-11e5-9409-8a6d61914846.png)

My files look like this, I tried to put the lang files at different locations
![image](https://cloud.githubusercontent.com/assets/13527958/13932281/92d13da8-efa7-11e5-8c06-de21919586e6.png)

Your example.php page is working fine for me. I first tried my changes over there, and it worked as expected, but it isn't working in my project.

I use the following code
![image](https://cloud.githubusercontent.com/assets/13527958/13932320/c34ff532-efa7-11e5-886d-e820afd17348.png)

I've also set my session variable to know which lang file to use.

You have an idea what I'm doing wrong? 

Thanks in advance!

**Comment by Zeebroek** [comment]
The variable '$this->langFilePath' gives the correct path, as you can see. I've got no clue at this point.

![image](https://cloud.githubusercontent.com/assets/13527958/13988790/d25c581a-f10d-11e5-9798-ccd38543a89c.png)

**Comment by amrography** [comment]
HOW!

**Comment by Zeebroek** [comment]
I don't remember, it's been 4 years, sorry.
Since those 4 years have passed, I learned to answer my own questions with the solution, don't worry.
