### ISSUE TITLE
Fallback language not merging files

### ISSUE THREAD

**Issue by bocall** [Philipp15b/php-i18n#32]
I have used the latest version of the source code to test out the fall back feature.  However, it looks like the set language is being loaded in twice instead of the set language and the fall back language.  This looks like a typo as instead of loading the passed in filename you load the set language.

When the above issue was sorted I ran into another small issue.  While the array_merge function merges the files neatly I needed to return the merged array in order for the combined language file to be made available.

I'm new to GitHub but am willing to pull the code with the changes I made for you to look over and merge with your if your happy with the changes but would need a little direction.

Merging fall back code:

`if ($this->mergeFallback)
                $config = self::array_extend($config, $this->load($this->getConfigFilename($this->fallbackLang)));`

load function:

`protected function load($filename) {
        $ext = substr(strrchr($filename, '.'), 1);
        switch ($ext) {
            case 'properties':
            case 'ini':
                $config = parse_ini_file($filename, true);
                break;`

array_merge return $a.

**Comment by Philipp15b** [comment]
Fixed by #34.
