### ISSUE TITLE
Make the dependency on Spyc external

### ISSUE THREAD

**Issue by PerWiklander** [Philipp15b/php-i18n#36]
Spyc has a composer package: https://packagist.org/packages/mustangostang/spyc, so there is no need to include it in this repository.

**Comment by Philipp15b** [comment]
Making `spyc` a composer dependency also makes composer a hard dependency of the project, which I was initially hesitant to commit to. I am happy to merge pull requests to fix this now though.

**Comment by PerWiklander** [comment]
I've started work on this PR now. I just have a question about the project license. The existing composer.json claims "CC BY-SA 3.0" while LICENSE.txt says "MIT", which one is it?
