### ISSUE TITLE
Merge Fallback

### ISSUE THREAD

**Issue by nikcani** [Philipp15b/php-i18n#37]
The option "mergeFallback" does not seem to do anything nor seems to be implement in the library.

**Comment by Philipp15b** [comment]
Are you certain? I'm pretty sure I see the code and the related commit 738bbe1d6580eaaabdc5006edc72a6767dc1115f. What exactly is your problem?

**Comment by Flynamic** [comment]
It's working in the newest commits, but not in the latest release (v3), which are from 2015. nikcani was probably confused by that.
