### ISSUE TITLE
Cache file

### ISSUE THREAD

**Issue by MarcelVe** [Philipp15b/php-i18n#41]
Hi, sorry my english is not so good.
This php-i18n is very good.
But I have a question: Is the cache file never deleted?

Thank you for your help.

**Comment by lcpaf** [comment]
I would also appreciate this question to answer. Seems to me that there isn't any routine to delete unused cache. That might be an issue for production servers.

**Comment by Philipp15b** [comment]
No, cache files need to be deleted manually. I don't think this is a problem, assuming language files are changed not too often.
