### ISSUE TITLE
Browser Issue

### ISSUE THREAD

**Issue by 1Luc1** [Philipp15b/php-i18n#45]
I got different results with two different browser. At the back is opera, in the front is firefox. So by default both browser show different results.

I added the following line to the example.php to see whats in the userlangs array.

`print_r($i18n->getUserLangs());
`

![browser](https://user-images.githubusercontent.com/25635952/28578627-9588583e-715a-11e7-9603-79316e9e4ff7.png)

OS: Ubuntu 16.04
Opera Version: 46.0 
Firefox Version: 54.0

**Comment by AlexanderKosianchuk** [comment]
As noted in README language may be applied throw several ways

...
GET parameter 'lang' ($_GET['lang'])
SESSION parameter 'lang' ($_SESSION['lang'])
HTTP_ACCEPT_LANGUAGE (can be multiple languages) ($_SERVER['HTTP_ACCEPT_LANGUAGE'])
Fallback language
...

I suppose that in one browser you have $_SESSION['lang'] = 'de',
But in another - dont.

Or if not - may be there is difference in $_SERVER['HTTP_ACCEPT_LANGUAGE']

**Comment by Philipp15b** [comment]
I assume this is resolved. Feel free to reopen if the problem still exists.
