### ISSUE TITLE
Use an array instead of constants in favor to allow literals with dots and dashes

### ISSUE THREAD

**Issue by Smolky** [Philipp15b/php-i18n#51]
I think that store the translations in the cache file using some king of array instead constants will allow to use "dashed" and "dots" in the names.

For example, this is not possible with the current implementation
`echo I::login.submit`

and provide some king of (for example)
`echo I::get('login.submit')`

It is just a thought to know your opinion

**Comment by Philipp15b** [comment]
This is a big change in how php-i18n works. It may even prevent some optimizations php caches can do now. Unless there is a bigger interest and a merge request for this, I don't think this feature will be added.
