### ISSUE TITLE
Elegant way to modify language from link <a href="xyz"...

### ISSUE THREAD

**Issue by SimonStolz** [Philipp15b/php-i18n#55]
Thanks a lot for providing i18n! As a php newby I had to figure out some things first with this package. My auto-detection works smooth and I am very happy already with this.
Now I am wondering:
 _Is there an easy way to make use of an HTML link to overwrite language parameters permanently for a user?_ 
I understand I can toggle "lang" via the URL GET parameter via adding  
> ?lang=de

My idea is to pass over the $_GET parameter to the $_SESSION variable. Yet even when I replicate the priority logic of _public function getUserLangs()_ and added the code below to my "header"-include. The language somehow does still not remain the one I have passed over, despite the echo correctly showing me `echo $_SESSION['lang']` is now "de", and is of type string, while `echo $_GET['lang']` and forcedLanguage are not set.
I would have expected:

1.  Forced Language? No
2.  Get Parameter? No
3.  Session Parameter? Yes: 'de' 

to be set.

**Comment by Philipp15b** [comment]
You want to save the language in your user session. I assume you either did not actually modify `$_SESSION['lang']` or have still a GET parameter present. Without the code this is difficult to tell. Feel free to reopen this issue if you think this is a bug in `php-i18n`.

**Comment by SimonStolz** [comment]
Thanks Philipp!
